"""added draft

Revision ID: 12184c15aac6
Revises: a2ddd1e6c7af
Create Date: 2016-11-14 10:41:24.807278

"""

# revision identifiers, used by Alembic.
revision = '12184c15aac6'
down_revision = 'a2ddd1e6c7af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('draft', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'draft')
    ### end Alembic commands ###
