"""add blog summary attr

Revision ID: 339b0274997c
Revises: b91503b14bc7
Create Date: 2016-10-26 23:13:20.744116

"""

# revision identifiers, used by Alembic.
revision = '339b0274997c'
down_revision = 'b91503b14bc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('summary', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'summary')
    ### end Alembic commands ###
