"""added tags and cats

Revision ID: 4ec81973e718
Revises: 12184c15aac6
Create Date: 2016-11-15 22:31:01.876275

"""

# revision identifiers, used by Alembic.
revision = '4ec81973e718'
down_revision = '12184c15aac6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('category', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    op.drop_table('tags')
    ### end Alembic commands ###
