"""deleted blog_count

Revision ID: 67ef895d2773
Revises: ad31788826a7
Create Date: 2016-11-22 23:41:51.061511

"""

# revision identifiers, used by Alembic.
revision = '67ef895d2773'
down_revision = 'ad31788826a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'blog_count')
    op.drop_column('tags', 'blog_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('blog_count', sa.INTEGER(), nullable=True))
    op.add_column('categories', sa.Column('blog_count', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
