"""init

Revision ID: 7539777725e4
Revises: None
Create Date: 2016-11-18 00:57:55.375834

"""

# revision identifiers, used by Alembic.
revision = '7539777725e4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs_tags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_tags',
    sa.Column('blog_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    ### end Alembic commands ###
