"""added user profile attrs

Revision ID: a2ddd1e6c7af
Revises: f8c391c8b689
Create Date: 2016-10-29 17:45:31.423699

"""

# revision identifiers, used by Alembic.
revision = 'a2ddd1e6c7af'
down_revision = 'f8c391c8b689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('blog_title', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blog_title')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
