"""added blog_count

Revision ID: ad31788826a7
Revises: None
Create Date: 2016-11-22 23:36:25.763141

"""

# revision identifiers, used by Alembic.
revision = 'ad31788826a7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('blog_count', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('blog_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'blog_count')
    op.drop_column('categories', 'blog_count')
    ### end Alembic commands ###
