"""add blog title attr

Revision ID: b91503b14bc7
Revises: 8374c996a2a2
Create Date: 2016-10-26 23:07:58.335812

"""

# revision identifiers, used by Alembic.
revision = 'b91503b14bc7'
down_revision = '8374c996a2a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('title', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'title')
    ### end Alembic commands ###
